#!/usr/bin/env python3
"""Build the 262-corpus-aligned anti-circularity held-out fixture for T11.

WHY this script exists (T11, owner decision 2026-06-11):
  The prior 234-corpus fixture is 0/30 aligned with the live 262 corpus (wiped
  UUIDs), so sweeps on it yield fabricated zeros. This builder produces a new
  fixture whose every positive query is anchored to a REAL skill in the 262-skill
  qwen3 corpus, and whose headline queries are derived from GENUINE developer
  problem statements typed in the source sessions — not from the skill's own
  use_when/description (that measures self-recall, not retrieval quality).

  The α=0 instrument gate (run later by the orchestrator): if this fixture does
  not crater MRR under α=0 (returning totally random results), it will be rebuilt.

INPUTS (already generated by earlier units):
  tests/e2e/reports/t11/session_problems.json
    {session_key: {transcript, uuid_suffix, skills_in_session:[names],
                   problems:[real developer problem statements]}}
  tests/e2e/reports/t11/corpus_inventory.json
    [{name, type, description, use_when:[...], tools:[...], artifacts:[...],
      invariants:[...], produces:[...], source_session_id, session_key}]

OUTPUT:
  tests/fixtures/retrieval_quality_262_corpus_labeled.json
    Fixture matching the schema consumed by scripts/retrieval_quality_live.py.
  tests/e2e/reports/t11/fixture_build_summary.json
    Per-stratum / per-split counts plus 3 sample queries per stratum.

QUERY STRATA:
  transcript  — grounded in a genuine problem statement from session_problems.json
                for the skill's source session. DOES NOT reuse skill name tokens.
  disjoint    — symptom/situation paraphrase in FRESH vocabulary; no skill-name or
                use_when token reuse. For sessions whose problems are thin/non-technical.
  lexical     — reuses a distinctive technical term from the skill description/name
                but NOT from multi-view-only fields.
  multiview   — the gold term lives ONLY in tools/artifacts/invariants, not in
                name/description/use_when. Stresses multi-view recall.
  use_when    — lightly reworded use_when phrasing (secondary / labeled stratum).
  negative    — adversarial: plausible software-dev queries that match NO corpus skill.

NO FAKES: real claude CLI synthesis only. Fails loud if claude is unreachable.
"""

import json
import random
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

# ─── paths ───────────────────────────────────────────────────────────────────

REPO = Path(__file__).resolve().parent.parent
CORPUS_INVENTORY = REPO / "tests/e2e/reports/t11/corpus_inventory.json"
SESSION_PROBLEMS = REPO / "tests/e2e/reports/t11/session_problems.json"
FIXTURE_OUT = REPO / "tests/fixtures/retrieval_quality_262_corpus_labeled.json"
SUMMARY_OUT = REPO / "tests/e2e/reports/t11/fixture_build_summary.json"

CLAUDE_MODEL = "claude-sonnet-4-6"

# Headline strata should dominate; use_when is a secondary stratum.
# Target totals per stratum (will adjust to ≥100 pos + ≥20 neg):
#   transcript  ~36   (headline)
#   disjoint    ~36   (headline)
#   lexical     ~24
#   multiview   ~16
#   use_when    ~12   (secondary)
#   negative    ~24

# tuning/held-out split target: ~55% tuning, ~45% held-out
SPLIT_TUNING_RATIO = 0.55

# Skill name prefixes that identify injected user-preference skills rather than
# technical patterns. These skills contain user instructions, not reusable engineering
# knowledge, and produce uninformative queries.
_PREFERENCE_SKILL_PREFIXES = (
    "Do not ",
    "When ",
    "Before ",
    "On ",
    "Ignore ",
    "Operate ",
    "Run ",
    "Add ",
    "Express ",
    "Skip ",
    "Use ",
    "Always ",
    "Never ",
    "Execution ",
    "Suppress ",
)


# ─── Claude CLI synthesis ─────────────────────────────────────────────────────

def invoke_claude(prompt: str) -> str:
    """Call the real claude CLI and return the raw model text.

    Uses the same invocation as scripts/retrieval_quality_live.py judge_query:
    ``claude --print --output-format json --model <model>``.
    The ``--output-format json`` envelope wraps model text in the ``.result`` key.

    Fails loud (raises RuntimeError) on any CLI error or non-zero exit code.
    Never silently falls back to a fake response.

    Args:
        prompt: The full prompt text to send to the model.

    Returns:
        The raw text content from the model's response (the ``.result`` value
        extracted from the JSON envelope, or raw stdout if envelope parsing fails).
    """
    proc = subprocess.run(
        ["claude", "--print", "--output-format", "json", "--model", CLAUDE_MODEL],
        input=prompt,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"claude CLI failed (rc={proc.returncode}): {proc.stderr[:500]}"
        )
    try:
        envelope = json.loads(proc.stdout)
        if isinstance(envelope, dict) and "result" in envelope:
            return envelope["result"]
    except json.JSONDecodeError:
        pass
    return proc.stdout


def parse_json_array_from_text(text: str, context: str = "") -> list:
    """Extract a JSON array from model output that may contain surrounding prose.

    Finds the first '[' and last ']' and parses between them.  Raises RuntimeError
    if no array brackets are found or if the JSON is malformed — never silently
    returns an empty list that masks a parse failure.

    Args:
        text: Raw model output text possibly containing a JSON array plus prose.
        context: Optional description of what was being parsed, for error messages.
    """
    text = text.strip()
    start = text.find("[")
    end = text.rfind("]")
    if start < 0 or end < 0 or end <= start:
        raise RuntimeError(
            f"No JSON array brackets found in claude output"
            f"{' for ' + context if context else ''}:\n{text[:400]}"
        )
    try:
        return json.loads(text[start : end + 1])
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Malformed JSON array in claude output"
            f"{' for ' + context if context else ''}: {exc}\n{text[start:end+1][:400]}"
        ) from exc


# ─── corpus loading and skill classification ──────────────────────────────────

def load_corpus(inventory_path: Path) -> tuple[list[dict], set[str]]:
    """Load the corpus inventory and return (skill_list, name_set).

    skill_list: all 262 skills as dicts.
    name_set: the set of all valid skill names for anchor validation.
    """
    skills = json.loads(inventory_path.read_text())
    return skills, {s["name"] for s in skills}


def load_session_problems(problems_path: Path) -> dict:
    """Load the session_problems.json mapping."""
    return json.loads(problems_path.read_text())


def usable_skills(skills: list[dict]) -> list[dict]:
    """Return skills that are candidates for positive queries.

    A skill is usable when it has a real type (not None) and a substantive
    description (>50 chars). Skills whose names start with any of the
    _PREFERENCE_SKILL_PREFIXES are excluded: those describe injected user
    preferences ('Do not respond to…', 'Always use…'), not technical engineering
    patterns, and produce uninformative queries.
    """
    return [
        s for s in skills
        if s.get("type") is not None
        and s.get("description")
        and len(s["description"]) > 50
        and not any(s["name"].startswith(prefix) for prefix in _PREFERENCE_SKILL_PREFIXES)
    ]


def skills_by_session(skills: list[dict]) -> dict[str, list[dict]]:
    """Group a skill list by session_key."""
    grouped: dict[str, list[dict]] = defaultdict(list)
    for s in skills:
        grouped[s["session_key"]].append(s)
    return dict(grouped)


def has_multiview_exclusive_terms(skill: dict) -> bool:
    """Return True if the skill has a specific term in tools/artifacts/invariants
    that does NOT appear in its name or description or use_when.

    Used to identify candidates for the 'multiview' stratum — queries whose gold
    term can only be found in the multi-view fields, stressing multi-view recall.
    """
    name_desc_usewhen = (
        skill["name"].lower()
        + " "
        + skill.get("description", "").lower()
        + " "
        + " ".join(skill.get("use_when", [])).lower()
    )
    for artifact in skill.get("artifacts", []):
        # Specific filenames (contain a dot) not mentioned in name/desc are good
        if "." in artifact and artifact.lower() not in name_desc_usewhen:
            return True
    for tool in skill.get("tools", []):
        # Specific tool names ≥5 chars not in name/desc
        if len(tool) >= 5 and tool.lower() not in name_desc_usewhen:
            return True
    for inv in skill.get("invariants", []):
        # Invariants often have precise technical terms
        words = [w for w in inv.split() if len(w) > 7]
        if any(w.lower() not in name_desc_usewhen for w in words[:3]):
            return True
    return False


# ─── query synthesis via real claude CLI ──────────────────────────────────────

def synthesize_transcript_and_disjoint_queries(
    skills_with_problems: list[dict],
    session_problems_map: dict,
) -> list[dict]:
    """Generate 'transcript' and 'disjoint' queries for a batch of skills.

    'transcript': grounded in a genuine problem statement from the source session.
      The query must describe what a developer experiencing that problem would search
      for, and must NOT reuse tokens from the skill's own name or use_when.

    'disjoint': a symptom/situation paraphrase that describes the skill's value in
      fresh vocabulary — zero token overlap with the skill name or use_when phrasing.

    Each item in skills_with_problems is a dict:
      {skill, problem_statement}  (problem_statement may be None if session had none)

    Returns a list of query dicts with keys: id, kind, text, anchor, relevant.
    (split is assigned later by the caller.)

    Calls the real claude CLI once per batch. Raises RuntimeError if synthesis fails.
    """
    if not skills_with_problems:
        return []

    skill_entries = []
    for i, item in enumerate(skills_with_problems):
        s = item["skill"]
        prob = item.get("problem_statement") or ""
        entry = (
            f'SKILL_{i+1}:\n'
            f'  name: {s["name"]}\n'
            f'  type: {s.get("type", "")}\n'
            f'  description: {s.get("description", "")}\n'
            f'  use_when:\n'
            + "".join(f'    - {u}\n' for u in s.get("use_when", []))
            + (f'  session_problem: {prob}\n' if prob else '')
        )
        skill_entries.append(entry)

    skills_text = "\n".join(skill_entries)
    prompt = f"""You are building a retrieval-quality evaluation fixture for an AI skill retrieval system.
For each skill below, generate TWO search queries that a developer would realistically type when they need this skill:

1. TRANSCRIPT query (kind=transcript): Ground this in the provided session_problem text (if present).
   Phrase it as a developer describing their actual situation/symptom, NOT as documentation search.
   The query MUST NOT contain any tokens from the skill's 'name' field.
   The query MUST NOT copy phrases from the skill's 'use_when' list.
   If no session_problem is provided, generate a disjoint query instead (mark kind=disjoint).

2. DISJOINT query (kind=disjoint): Describe the same situation in completely FRESH vocabulary.
   Zero token overlap with the skill name or use_when phrasing.
   Think: "how would a developer describe this symptom to a colleague who knows nothing about this skill?"

Both queries must be realistic developer phrasing — a question or situation description, not a keyword list.
Both queries must clearly point to this specific skill as the most relevant answer.

Skills:
{skills_text}

Respond with EXACTLY a JSON array, one object per skill, in this format:
[
  {{
    "skill_index": 1,
    "skill_name": "<exact name from above>",
    "transcript_query": "<realistic developer query grounded in the problem statement, or empty string if no problem>",
    "disjoint_query": "<fresh vocabulary paraphrase of skill intent>"
  }},
  ...
]

JSON:"""

    raw = invoke_claude(prompt)
    items = parse_json_array_from_text(raw, context="transcript/disjoint batch")

    queries = []
    for item_data in items:
        skill_name = item_data.get("skill_name", "")
        idx = item_data.get("skill_index", 0)
        transcript_q = (item_data.get("transcript_query") or "").strip()
        disjoint_q = (item_data.get("disjoint_query") or "").strip()

        if not skill_name:
            continue

        if transcript_q:
            queries.append({
                "id": f"t11-transcript-{_slug(skill_name)}",
                "kind": "transcript",
                "text": transcript_q,
                "anchor": skill_name,
                "relevant": [skill_name],
            })

        if disjoint_q:
            queries.append({
                "id": f"t11-disjoint-{_slug(skill_name)}",
                "kind": "disjoint",
                "text": disjoint_q,
                "anchor": skill_name,
                "relevant": [skill_name],
            })

    return queries


def synthesize_lexical_queries(skill_batch: list[dict]) -> list[dict]:
    """Generate 'lexical' queries for a batch of skills.

    A lexical query reuses a distinctive technical term from the skill's
    description or name (not multi-view-only fields) to stress lexical recall.
    The query must be realistic developer phrasing, not a keyword dump.

    Returns a list of query dicts (split assigned later).
    Raises RuntimeError if claude CLI fails.
    """
    if not skill_batch:
        return []

    skill_entries = []
    for i, s in enumerate(skill_batch):
        entry = (
            f'SKILL_{i+1}:\n'
            f'  name: {s["name"]}\n'
            f'  description: {s.get("description", "")}\n'
        )
        skill_entries.append(entry)

    skills_text = "\n".join(skill_entries)
    prompt = f"""You are building a retrieval-quality evaluation fixture.
For each skill below, generate ONE 'lexical' search query.

A LEXICAL query reuses at least one distinctive technical term that appears in
the skill's name or description — the kind of specific vocabulary a developer
would use when they already know the rough domain.
The query must be a realistic sentence or question, not a keyword list.

Skills:
{skills_text}

Respond with EXACTLY a JSON array, one object per skill:
[
  {{
    "skill_index": 1,
    "skill_name": "<exact name>",
    "lexical_query": "<realistic developer query using a term from the skill description>"
  }},
  ...
]

JSON:"""

    raw = invoke_claude(prompt)
    items = parse_json_array_from_text(raw, context="lexical batch")

    queries = []
    for item_data in items:
        skill_name = item_data.get("skill_name", "")
        q_text = (item_data.get("lexical_query") or "").strip()
        if skill_name and q_text:
            queries.append({
                "id": f"t11-lexical-{_slug(skill_name)}",
                "kind": "lexical",
                "text": q_text,
                "anchor": skill_name,
                "relevant": [skill_name],
            })
    return queries


def synthesize_multiview_queries(skill_batch: list[dict]) -> list[dict]:
    """Generate 'multiview' queries for skills that have terms exclusive to
    their tools/artifacts/invariants fields.

    A multiview query uses a term that ONLY appears in the multi-view fields
    (tools, artifacts, invariants) — not in name, description, or use_when.
    This stresses multi-view recall: a retrieval system that only indexes the
    summary embedding will miss these.

    Returns a list of query dicts (split assigned later).
    Raises RuntimeError if claude CLI fails.
    """
    if not skill_batch:
        return []

    skill_entries = []
    for i, s in enumerate(skill_batch):
        entry = (
            f'SKILL_{i+1}:\n'
            f'  name: {s["name"]}\n'
            f'  description: {s.get("description", "")}\n'
            f'  tools: {json.dumps(s.get("tools", []))}\n'
            f'  artifacts: {json.dumps(s.get("artifacts", []))}\n'
            f'  invariants: {json.dumps(s.get("invariants", []))}\n'
        )
        skill_entries.append(entry)

    skills_text = "\n".join(skill_entries)
    prompt = f"""You are building a retrieval-quality evaluation fixture.
For each skill below, generate ONE 'multiview' search query.

A MULTIVIEW query must use a specific technical term that appears ONLY in the skill's
tools, artifacts, or invariants — NOT in its name or description.
For example: a specific filename, a specific CLI tool name, or a precise constraint
from the invariants list.
The query must be realistic developer phrasing (a situation or question), not a keyword dump.
The goal: a retrieval system that only uses the skill name/description will MISS this query,
but one that also indexes tools/artifacts/invariants will find it.

Skills:
{skills_text}

Respond with EXACTLY a JSON array, one object per skill:
[
  {{
    "skill_index": 1,
    "skill_name": "<exact name>",
    "multiview_query": "<realistic developer query using a term only in tools/artifacts/invariants>",
    "gold_term": "<the specific term from tools/artifacts/invariants that the query uses>"
  }},
  ...
]

JSON:"""

    raw = invoke_claude(prompt)
    items = parse_json_array_from_text(raw, context="multiview batch")

    queries = []
    for item_data in items:
        skill_name = item_data.get("skill_name", "")
        q_text = (item_data.get("multiview_query") or "").strip()
        if skill_name and q_text:
            queries.append({
                "id": f"t11-multiview-{_slug(skill_name)}",
                "kind": "multiview",
                "text": q_text,
                "anchor": skill_name,
                "relevant": [skill_name],
            })
    return queries


def synthesize_use_when_queries(skill_batch: list[dict]) -> list[dict]:
    """Generate 'use_when' queries (secondary stratum) for a batch of skills.

    A use_when query is a lightly reworded version of one of the skill's
    use_when conditions. This is the most generous query kind (closest to
    self-recall) and is labeled as secondary so the sweep can report it
    separately and discount it in the primary MRR headline.

    Returns a list of query dicts (split assigned later).
    Raises RuntimeError if claude CLI fails.
    """
    if not skill_batch:
        return []

    # Only pick skills that have use_when content
    batch_with_usewhen = [s for s in skill_batch if s.get("use_when")]
    if not batch_with_usewhen:
        return []

    skill_entries = []
    for i, s in enumerate(batch_with_usewhen):
        use_when_text = "\n".join(f"    - {u}" for u in s.get("use_when", []))
        entry = (
            f'SKILL_{i+1}:\n'
            f'  name: {s["name"]}\n'
            f'  use_when:\n{use_when_text}\n'
        )
        skill_entries.append(entry)

    skills_text = "\n".join(skill_entries)
    prompt = f"""You are building a retrieval-quality evaluation fixture.
For each skill below, generate ONE 'use_when' query.

A USE_WHEN query is derived from the skill's use_when conditions but LIGHTLY REWORDED
— you must paraphrase the condition in fresh phrasing, not copy it verbatim.
Pick the most specific and distinctive use_when condition (avoid generic ones).
The query must be realistic developer phrasing.

Skills:
{skills_text}

Respond with EXACTLY a JSON array, one object per skill:
[
  {{
    "skill_index": 1,
    "skill_name": "<exact name>",
    "use_when_query": "<lightly reworded paraphrase of one use_when condition>"
  }},
  ...
]

JSON:"""

    raw = invoke_claude(prompt)
    items = parse_json_array_from_text(raw, context="use_when batch")

    queries = []
    for item_data in items:
        skill_name = item_data.get("skill_name", "")
        q_text = (item_data.get("use_when_query") or "").strip()
        if skill_name and q_text:
            queries.append({
                "id": f"t11-usewhen-{_slug(skill_name)}",
                "kind": "use_when",
                "text": q_text,
                "anchor": skill_name,
                "relevant": [skill_name],
            })
    return queries


def synthesize_negative_queries(count: int) -> list[dict]:
    """Generate adversarial negative queries: plausible software-dev queries
    that match NO skill in the 262-skill corpus.

    The corpus covers: Rust/cargo errors, Docker multi-stage builds, Postgres
    migrations, embeddings/RAG, multi-agent orchestration, Tokio async, Qdrant,
    Redis, git workflows, clippy lints, and session extraction.

    A good negative is: realistic developer search phrasing that sounds plausible
    but targets a DIFFERENT domain, language, or problem that the corpus has NO skill for.

    Returns a list of negative query dicts with anchor=null, relevant=[].
    Raises RuntimeError if claude CLI fails.
    """
    prompt = f"""You are building a retrieval-quality evaluation fixture for a skill retrieval system.
The skill corpus covers: Rust/cargo errors, Docker builds, Postgres SQL migrations, embedding/RAG pipelines,
multi-agent orchestration, Tokio async Rust, Qdrant vector DB, Redis streams, git commit workflows,
clippy lint fixing, and AI session transcript extraction.

Generate exactly {count} ADVERSARIAL NEGATIVE queries. Each must be:
1. A realistic software-developer search query (not obviously fake).
2. About a topic that the corpus has NO relevant skill for — different language, domain, or problem.
3. Specific enough that it could NOT be coincidentally answered by any of the above topics.

Good examples: frontend React state management, Python Flask routing, Kubernetes YAML config,
Java Spring Boot dependency injection, C# NuGet packaging, AWS Lambda cold starts, SQL Server
stored procedures, Nginx load balancer config.

Respond with EXACTLY a JSON array of {count} objects:
[
  {{
    "query": "<realistic developer query that matches nothing in the Rust/Docker/PG/RAG/agent corpus>"
  }},
  ...
]

JSON:"""

    raw = invoke_claude(prompt)
    items = parse_json_array_from_text(raw, context="negatives")

    queries = []
    for i, item_data in enumerate(items[:count]):
        q_text = (item_data.get("query") or "").strip()
        if q_text:
            queries.append({
                "id": f"t11-neg-{i+1:02d}",
                "kind": "negative",
                "text": q_text,
                "anchor": None,
                "relevant": [],
            })
    return queries


# ─── validation ───────────────────────────────────────────────────────────────

def validate_anchors(queries: list[dict], valid_names: set[str]) -> None:
    """Validate that every positive query's anchor and relevant list contains
    only names that exist in the corpus.

    Fails loud (raises RuntimeError) listing ALL misses — never silently drops
    a query with an invalid anchor. The caller must fix the source before proceeding.

    Args:
        queries: All query dicts from the fixture (positives and negatives mixed).
        valid_names: The set of all 262 skill names from corpus_inventory.
    """
    anchor_misses = []
    relevant_misses = []
    for q in queries:
        if q["kind"] == "negative":
            continue
        anchor = q.get("anchor")
        if anchor and anchor not in valid_names:
            anchor_misses.append(f"  query {q['id']!r}: anchor {anchor!r}")
        for r in q.get("relevant", []):
            if r not in valid_names:
                relevant_misses.append(f"  query {q['id']!r}: relevant {r!r}")

    if anchor_misses or relevant_misses:
        lines = ["ANCHOR VALIDATION FAILED — misses in 262 corpus:"]
        if anchor_misses:
            lines.append("  Bad anchors:")
            lines.extend(anchor_misses)
        if relevant_misses:
            lines.append("  Bad relevant entries:")
            lines.extend(relevant_misses)
        raise RuntimeError("\n".join(lines))


# ─── split assignment ─────────────────────────────────────────────────────────

def assign_splits(queries: list[dict], tuning_ratio: float) -> list[dict]:
    """Assign tuning/held_out splits to queries.

    Positives are split per anchor skill: each anchor's queries go entirely into
    one split (so the two splits test on disjoint anchor sets, preventing
    information leakage). The anchor assignment is randomized, then balanced to
    the target ratio.

    Negatives are split proportionally across both splits.

    Returns the same list with 'split' field filled in on every query.
    """
    # Group positive queries by anchor
    by_anchor: dict[str, list[dict]] = defaultdict(list)
    negatives = []
    for q in queries:
        if q["kind"] == "negative":
            negatives.append(q)
        else:
            by_anchor[q["anchor"]].append(q)

    anchors = list(by_anchor.keys())
    random.shuffle(anchors)

    n_tuning = round(len(anchors) * tuning_ratio)
    tuning_anchors = set(anchors[:n_tuning])
    held_out_anchors = set(anchors[n_tuning:])

    result = []
    for q in queries:
        q = dict(q)  # copy to avoid mutation
        if q["kind"] == "negative":
            continue  # handled below
        split = "tuning" if q["anchor"] in tuning_anchors else "held_out"
        q["split"] = split
        result.append(q)

    # Split negatives proportionally
    neg_tuning_count = round(len(negatives) * tuning_ratio)
    for i, neg in enumerate(negatives):
        neg = dict(neg)
        neg["split"] = "tuning" if i < neg_tuning_count else "held_out"
        result.append(neg)

    return result


# ─── helpers ──────────────────────────────────────────────────────────────────

def _slug(name: str) -> str:
    """Convert a skill name to a short, URL-safe id fragment (max 40 chars)."""
    slug = name.lower().replace(" ", "-").replace("/", "-").replace("_", "-")
    # Remove characters other than alphanumeric and dash
    slug = "".join(c for c in slug if c.isalnum() or c == "-")
    return slug[:40].rstrip("-")


def _print_progress(msg: str) -> None:
    """Print a progress line to stderr so stdout remains clean for piped use."""
    print(f"[build_t11_fixture] {msg}", file=sys.stderr)


def _chunk(lst: list, size: int) -> list[list]:
    """Split a list into chunks of at most `size` items."""
    return [lst[i : i + size] for i in range(0, len(lst), size)]


# ─── main build pipeline ──────────────────────────────────────────────────────

def build_fixture() -> None:
    """Orchestrate the complete fixture build.

    Loads artifacts → selects gold skills → calls claude for each stratum →
    validates anchors → assigns splits → writes fixture + summary.

    Raises RuntimeError on any failure. Does NOT silently continue with partial
    results — the fixture must be complete and valid or the build fails.
    """
    _print_progress("Loading corpus inventory and session problems...")
    skills, valid_names = load_corpus(CORPUS_INVENTORY)
    session_problems = load_session_problems(SESSION_PROBLEMS)

    # ── select usable skills ─────────────────────────────────────────────────
    candidate_skills = usable_skills(skills)
    _print_progress(f"Usable skills for query authoring: {len(candidate_skills)}")

    by_session = skills_by_session(candidate_skills)

    # ── select gold skills for transcript/disjoint strata ───────────────────
    # For transcript: the session must have a real technical problem (>80 chars)
    # AND the skill must be in that session.
    # Pick 1-2 skills per session with problems to spread gold across sessions.
    transcript_targets: list[dict] = []  # {skill, problem_statement}

    for session_key, session_data in session_problems.items():
        technical_problems = [
            p for p in session_data.get("problems", [])
            if len(p) > 80 and not _is_trivial_problem(p)
        ]
        session_skills_in_corpus = by_session.get(session_key, [])
        if not technical_problems or not session_skills_in_corpus:
            continue

        # Pick the most technical problem from the session
        best_problem = max(technical_problems, key=len)

        # Pick 1-2 skills from this session
        chosen = session_skills_in_corpus[:2]
        for s in chosen:
            transcript_targets.append({
                "skill": s,
                "problem_statement": best_problem,
            })

    _print_progress(f"Transcript targets: {len(transcript_targets)} (across sessions)")

    # ── stratum 1+2: transcript + disjoint (batches of 8) ───────────────────
    all_transcript_disjoint: list[dict] = []
    batches = _chunk(transcript_targets, 5)
    for i, batch in enumerate(batches):
        _print_progress(
            f"Synthesizing transcript/disjoint batch {i+1}/{len(batches)} "
            f"({len(batch)} skills)..."
        )
        qs = synthesize_transcript_and_disjoint_queries(batch, session_problems)
        all_transcript_disjoint.extend(qs)
        _print_progress(f"  → {len(qs)} queries generated")

    _print_progress(
        f"Transcript/disjoint total: {len(all_transcript_disjoint)}"
    )

    # ── stratum 3: lexical (pick from all sessions, 1 per skill) ─────────────
    # Choose a balanced cross-section of skills for lexical queries
    lexical_skills = _select_balanced_sample(candidate_skills, target_count=30)
    lexical_queries: list[dict] = []
    for batch in _chunk(lexical_skills, 6):
        _print_progress(f"Synthesizing lexical batch ({len(batch)} skills)...")
        qs = synthesize_lexical_queries(batch)
        lexical_queries.extend(qs)
    _print_progress(f"Lexical total: {len(lexical_queries)}")

    # ── stratum 4: multiview (only for skills with exclusive MV terms) ────────
    mv_candidates = [s for s in candidate_skills if has_multiview_exclusive_terms(s)]
    mv_skills = _select_balanced_sample(mv_candidates, target_count=20)
    multiview_queries: list[dict] = []
    for batch in _chunk(mv_skills, 5):
        _print_progress(f"Synthesizing multiview batch ({len(batch)} skills)...")
        qs = synthesize_multiview_queries(batch)
        multiview_queries.extend(qs)
    _print_progress(f"Multiview total: {len(multiview_queries)}")

    # ── stratum 5: use_when (secondary stratum, smaller count) ───────────────
    uw_skills = _select_balanced_sample(
        [s for s in candidate_skills if s.get("use_when")], target_count=15
    )
    use_when_queries: list[dict] = []
    for batch in _chunk(uw_skills, 6):
        _print_progress(f"Synthesizing use_when batch ({len(batch)} skills)...")
        qs = synthesize_use_when_queries(batch)
        use_when_queries.extend(qs)
    _print_progress(f"Use_when total: {len(use_when_queries)}")

    # ── stratum 6: negatives ──────────────────────────────────────────────────
    _print_progress("Synthesizing negative queries...")
    negative_queries = synthesize_negative_queries(count=25)
    _print_progress(f"Negatives total: {len(negative_queries)}")

    # ── assemble all queries ──────────────────────────────────────────────────
    all_positive = (
        all_transcript_disjoint
        + lexical_queries
        + multiview_queries
        + use_when_queries
    )
    all_queries = all_positive + negative_queries

    _print_progress(f"Total before dedup: {len(all_queries)} queries")

    # Deduplicate by id (keep first occurrence)
    seen_ids: set[str] = set()
    deduped: list[dict] = []
    for q in all_queries:
        if q["id"] not in seen_ids:
            seen_ids.add(q["id"])
            deduped.append(q)
    all_queries = deduped

    # ── validate anchors ──────────────────────────────────────────────────────
    _print_progress("Validating all anchors against corpus names...")
    validate_anchors(all_queries, valid_names)
    _print_progress("Anchor validation passed.")

    # ── count checks ─────────────────────────────────────────────────────────
    positives = [q for q in all_queries if q["kind"] != "negative"]
    negatives = [q for q in all_queries if q["kind"] == "negative"]
    _print_progress(
        f"Counts: {len(positives)} positives, {len(negatives)} negatives"
    )

    if len(positives) < 100:
        raise RuntimeError(
            f"Fixture has only {len(positives)} positive queries; need ≥100. "
            "Adjust batch sizes or add more sessions."
        )
    if len(negatives) < 20:
        raise RuntimeError(
            f"Fixture has only {len(negatives)} negative queries; need ≥20."
        )

    # ── assign splits ─────────────────────────────────────────────────────────
    _print_progress("Assigning tuning/held_out splits...")
    random.seed(42)
    all_queries_with_split = assign_splits(all_queries, SPLIT_TUNING_RATIO)

    # ── build fixture document ────────────────────────────────────────────────
    stratum_counts = _count_by_field(all_queries_with_split, "kind")
    split_counts = _count_by_field(all_queries_with_split, "split")
    distinct_gold_skills = len(
        {q["anchor"] for q in all_queries_with_split if q.get("anchor")}
    )
    distinct_sessions = len(
        {
            next(
                (s["session_key"] for s in skills if s["name"] == q.get("anchor")),
                None,
            )
            for q in all_queries_with_split
            if q.get("anchor")
        }
        - {None}
    )

    fixture = {
        "_description": (
            "Anti-circularity retrieval-quality fixture for the 262-skill qwen3 corpus (T11). "
            "Headline queries (transcript/disjoint) are derived from GENUINE developer problem "
            "statements typed in the source sessions, NOT from the skills' own use_when or "
            "description — that ensures the fixture measures real retrieval discriminability, "
            "not self-recall. Lexical queries use terms from skill descriptions. Multiview "
            "queries use terms that appear ONLY in tools/artifacts/invariants. Use_when queries "
            "are a labeled secondary stratum (lightly reworded use_when). Negatives are "
            "adversarial plausible queries that match no corpus skill. Built 2026-06-11."
        ),
        "_authoring_protocol": (
            "Queries generated by the real claude CLI (claude-sonnet-4-6 via "
            "claude --print --output-format json). Anchors validated against the 262 corpus name "
            "set before commit. No fabricated/templated queries. "
            "Gold skills drawn from 24 source sessions via session_problems.json + "
            "corpus_inventory.json prepared by scripts/extract_t11_session_problems.py."
        ),
        "_strata": {
            "transcript": "Grounded in a genuine developer problem statement from the source session. "
                          "Does not reuse skill name tokens.",
            "disjoint": "Intent paraphrase in fresh vocabulary; zero token overlap with skill name/use_when.",
            "lexical": "Uses a distinctive technical term from the skill name/description.",
            "multiview": "Uses a term that appears ONLY in tools/artifacts/invariants (not name/desc/use_when).",
            "use_when": "SECONDARY STRATUM: lightly reworded paraphrase of one use_when condition.",
            "negative": "Adversarial: plausible software-dev query that matches no corpus skill.",
        },
        "_split": "tuning/held_out disjoint by anchor skill (~55/45); negatives proportionally split",
        "_counts": {
            "strata": stratum_counts,
            "splits": split_counts,
            "distinct_gold_skills": distinct_gold_skills,
            "distinct_sessions": distinct_sessions,
        },
        "queries": all_queries_with_split,
    }

    # ── write fixture ─────────────────────────────────────────────────────────
    FIXTURE_OUT.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_OUT.write_text(json.dumps(fixture, indent=1, ensure_ascii=False))
    _print_progress(f"Fixture written to {FIXTURE_OUT}")

    # ── write summary ─────────────────────────────────────────────────────────
    summary = {
        "stratum_counts": stratum_counts,
        "split_counts": split_counts,
        "distinct_gold_skill_count": distinct_gold_skills,
        "distinct_session_count": distinct_sessions,
        "total_queries": len(all_queries_with_split),
        "samples_by_stratum": _sample_queries_by_stratum(all_queries_with_split),
    }
    SUMMARY_OUT.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY_OUT.write_text(json.dumps(summary, indent=2, ensure_ascii=False))
    _print_progress(f"Summary written to {SUMMARY_OUT}")

    # ── final report ─────────────────────────────────────────────────────────
    _print_progress("Build complete.")
    _print_progress(f"  Positives: {len(positives)}")
    _print_progress(f"  Negatives: {len(negatives)}")
    _print_progress(f"  Strata: {stratum_counts}")
    _print_progress(f"  Splits: {split_counts}")
    _print_progress(f"  Distinct gold skills: {distinct_gold_skills}")
    _print_progress(f"  Distinct sessions: {distinct_sessions}")


# ─── internal helpers ─────────────────────────────────────────────────────────

def _is_trivial_problem(problem: str) -> bool:
    """Return True if the problem statement is operational steering with no
    technical content (e.g. 'commit and push', 'yes proceed').

    These statements don't seed meaningful 'transcript' queries because they
    describe meta-actions, not developer technical problems.
    """
    lowered = problem.lower().strip()
    trivial_patterns = (
        "commit and push",
        "commit and proceed",
        "proceed to next",
        "give me the prompt",
        "commit it and then",
        "yes commit",
        "yes yes it",
        "commit everything",
        "add those untracked",
        "add everything to the commit",
        "is everything committed",
        "is everything logged",
        "are the new tickets",
        "\\\\wsl",
    )
    return any(lowered.startswith(p) for p in trivial_patterns)


def _select_balanced_sample(skills: list[dict], target_count: int) -> list[dict]:
    """Select up to `target_count` skills spread across as many sessions as
    possible (round-robin across sessions), to ensure gold skills span the corpus.

    Returns a list of at most `target_count` skills.
    """
    by_session: dict[str, list[dict]] = defaultdict(list)
    for s in skills:
        by_session[s["session_key"]].append(s)

    session_queues = {k: list(v) for k, v in by_session.items()}
    result = []
    while len(result) < target_count:
        added_this_round = False
        for session_key in list(session_queues.keys()):
            if not session_queues[session_key]:
                continue
            result.append(session_queues[session_key].pop(0))
            added_this_round = True
            if len(result) >= target_count:
                break
        if not added_this_round:
            break

    return result


def _count_by_field(queries: list[dict], field: str) -> dict[str, int]:
    """Return a frequency count of query values for the given field key."""
    counts: dict[str, int] = defaultdict(int)
    for q in queries:
        counts[str(q.get(field, "unknown"))] += 1
    return dict(sorted(counts.items()))


def _sample_queries_by_stratum(queries: list[dict], n: int = 3) -> dict[str, list[dict]]:
    """Return up to `n` sample queries per stratum for the build summary."""
    by_stratum: dict[str, list[dict]] = defaultdict(list)
    for q in queries:
        by_stratum[q["kind"]].append(q)

    return {
        kind: [
            {"id": q["id"], "text": q["text"], "anchor": q.get("anchor"), "split": q.get("split")}
            for q in qs[:n]
        ]
        for kind, qs in by_stratum.items()
    }


# ─── entrypoint ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    build_fixture()
