BEGIN;

-- Add a `source` column to `community_skills` so a skill can belong to both an
-- HDBSCAN-derived cluster community AND a tag-based community at the same time
-- (dual membership).  Previously the PK was (community_id, skill_id), allowing
-- at most one row per community+skill pair.  With dual membership a skill may
-- appear twice in the same community if—hypothetically—the same community were
-- generated by both sources, so the PK becomes (community_id, skill_id, source).
--
-- Design rationale:
--   CONTEXT.md §2.2 promises that skills belong to both semantic HDBSCAN clusters
--   AND tag-based communities.  This column is the single structural change that
--   makes the dual-membership write path possible without widening any other table.
--
-- Compatibility:
--   `ADD COLUMN … NOT NULL DEFAULT 'tag'` is non-rewriting on Postgres 11+.
--   Existing rows (all written by the old tag-only path) receive source='tag' so
--   the constraint is satisfied immediately.  The new PK includes `source`, so
--   the old unique constraint on (community_id, skill_id) is implicitly widened —
--   no explicit DROP of the old constraint is needed because the whole table is
--   deleted and re-inserted inside each atomic rebuild transaction
--   (replace_snapshot_and_bump_version deletes community_skills before re-inserting).
--
-- Schema scoping (critical):
--   Every catalog lookup below is keyed on `'community_skills'::regclass`, which
--   resolves to the single table on the current `search_path`.  An earlier version
--   matched `pg_class.relname = 'community_skills'` / `information_schema.columns`,
--   which matches the table in EVERY schema — under per-run schema isolation
--   (test namespaces) that returns multiple rows and the `DROP CONSTRAINT`
--   subquery fails with "more than one row returned by a subquery used as an
--   expression". `regclass` scoping fixes that and is correct for both the single
--   public schema and isolated per-run schemas.
--
-- Idempotency (run-twice-clean):
--   Both DO blocks guard on the post-state (column present / PK already includes
--   `source`) so a re-run is a no-op (no error, no data change).
--
-- Human gate: APPROVED 2026-06-05 (dual-membership community schema, migration 006,
--   follows 005_skill_source_paths.sql).
--
-- Rollback (down):
--   ALTER TABLE community_skills DROP COLUMN IF EXISTS source;
--   -- Restore old PK:
--   ALTER TABLE community_skills DROP CONSTRAINT IF EXISTS community_skills_pkey;
--   ALTER TABLE community_skills ADD PRIMARY KEY (community_id, skill_id);

-- Step 1: add the source column (idempotent; scoped to the current schema's
-- table via regclass so a `source` column in another schema does not mask a
-- missing one here).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'community_skills'::regclass
          AND attname = 'source'
          AND NOT attisdropped
    ) THEN
        ALTER TABLE community_skills
            ADD COLUMN source TEXT NOT NULL DEFAULT 'tag'
                CHECK (source IN ('hdbscan', 'tag'));
    END IF;
END
$$;

-- Step 2: widen the primary key to include source so dual membership is
-- structurally enforced.  Scoped to the current schema's table via regclass:
-- the constraint lookups return at most one row even when several schemas each
-- hold a `community_skills` table (per-run isolation).
DO $$
DECLARE
    existing_pk_name text;
    pk_already_includes_source boolean;
BEGIN
    -- Second-run safety: skip entirely if the PK already includes `source`.
    SELECT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_attribute a
            ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
        WHERE c.conrelid = 'community_skills'::regclass
          AND c.contype = 'p'
          AND a.attname = 'source'
    ) INTO pk_already_includes_source;

    IF NOT pk_already_includes_source THEN
        -- Drop whichever PK currently exists (exactly one, via regclass).
        SELECT c.conname
        INTO existing_pk_name
        FROM pg_constraint c
        WHERE c.conrelid = 'community_skills'::regclass
          AND c.contype = 'p';

        IF existing_pk_name IS NOT NULL THEN
            EXECUTE format(
                'ALTER TABLE community_skills DROP CONSTRAINT %I',
                existing_pk_name
            );
        END IF;

        ALTER TABLE community_skills
            ADD CONSTRAINT community_skills_pkey
            PRIMARY KEY (community_id, skill_id, source);
    END IF;
END
$$;

COMMIT;
