BEGIN;

-- Add a `source` column to `community_skills` so a skill can belong to both an
-- HDBSCAN-derived cluster community AND a tag-based community at the same time
-- (dual membership).  Previously the PK was (community_id, skill_id), allowing
-- at most one row per community+skill pair.  With dual membership a skill may
-- appear twice in the same community if—hypothetically—the same community were
-- generated by both sources, so the PK becomes (community_id, skill_id, source).
--
-- Design rationale:
--   CONTEXT.md §2.2 promises that skills belong to both semantic HDBSCAN clusters
--   AND tag-based communities.  This column is the single structural change that
--   makes the dual-membership write path possible without widening any other table.
--
-- Compatibility:
--   `ADD COLUMN … NOT NULL DEFAULT 'tag'` is non-rewriting on Postgres 11+.
--   Existing rows (all written by the old tag-only path) receive source='tag' so
--   the constraint is satisfied immediately.  The new PK includes `source`, so
--   the old unique constraint on (community_id, skill_id) is implicitly widened —
--   no explicit DROP of the old constraint is needed because the whole table is
--   deleted and re-inserted inside each atomic rebuild transaction
--   (replace_snapshot_and_bump_version deletes community_skills before re-inserting).
--
-- Idempotency (run-twice-clean):
--   Both statements use `IF NOT EXISTS` / `IF EXISTS` guards so a re-run is a
--   no-op (no error, no data change).
--
-- Human gate: APPROVED 2026-06-05 (dual-membership community schema, migration 006,
--   follows 005_skill_source_paths.sql).
--
-- Rollback (down):
--   ALTER TABLE community_skills DROP COLUMN IF EXISTS source;
--   -- Restore old PK:
--   ALTER TABLE community_skills DROP CONSTRAINT IF EXISTS community_skills_pkey;
--   ALTER TABLE community_skills ADD PRIMARY KEY (community_id, skill_id);

-- Step 1: add the source column (idempotent — IF NOT EXISTS guard via a DO block).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'community_skills'
          AND column_name = 'source'
    ) THEN
        ALTER TABLE community_skills
            ADD COLUMN source TEXT NOT NULL DEFAULT 'tag'
                CHECK (source IN ('hdbscan', 'tag'));
    END IF;
END
$$;

-- Step 2: widen the primary key to include source so dual membership is
-- structurally enforced.  The old PK constraint must be dropped first.
-- Guard: only act when the old (2-column) PK still exists.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = 'community_skills'
          AND c.contype = 'p'
    ) THEN
        -- Drop whichever PK currently exists (old 2-col or new 3-col).
        -- The name is system-assigned so we look it up dynamically.
        EXECUTE (
            SELECT format('ALTER TABLE community_skills DROP CONSTRAINT %I', c.conname)
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            WHERE t.relname = 'community_skills'
              AND c.contype = 'p'
        );
    END IF;

    -- Re-create PK as (community_id, skill_id, source) only if it does not
    -- already have 3 columns (second-run safety).
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
        WHERE t.relname = 'community_skills'
          AND c.contype = 'p'
          AND a.attname = 'source'
    ) THEN
        ALTER TABLE community_skills
            ADD CONSTRAINT community_skills_pkey
            PRIMARY KEY (community_id, skill_id, source);
    END IF;
END
$$;

COMMIT;
